name: Docker Image CI

on:
  push:
<<<<<<< HEAD
    branches: [ master ]

jobs: 

  build:

=======
    branches:
      - master
      - main
    paths:
      - ".github/workflows/deploy-image.yml"
      - "bin/entry_point.sh"
      - "Dockerfile"
      - "Gemfile"
      - "Gemfile.lock"
      - "package.json"
      - "package-lock.json"

jobs:
  build:
>>>>>>> upstream/main
    runs-on: ubuntu-latest
    if: github.repository_owner == 'alshedivat'

    steps:
<<<<<<< HEAD
    - name: Checkout
      uses: actions/checkout@v3
    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: amirpourmand/al-folio
=======
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: amirpourmand/al-folio
>>>>>>> upstream/main
